PAGINATION_PAGE_SIZE = 6

USER = 'user'
ADMIN = 'admin'

USER_ROLES = [
    (USER, 'user'),
    (ADMIN, 'admin'),
]

DEFAULT_FOLLOW_RECIPE_LIMIT = 4
MAX_MODEL_FIELD_LENGTH = 200
MAX_USER_MODEL_FIELD_LENGTH = 150

USERNAME_REGEX = r'^[\w.@+-]+$'
