version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:

services:

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/

  backend:
    build: ./backend/    
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - frontend
    env_file:
      - .env

  gateway:
    image: nginx:1.19.3
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
    ports:
      - "80:80"