# Generated by Django 3.2.6 on 2023-12-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписчика', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
